replicaCount: 2

image:
  repository: lehardocker/gitops-app
  tag: "dev-21dab60"
  pullPolicy: IfNotPresent

deploymentStrategy: deployment
# options:
# deployment
# canary
# bluegreen  

serviceAccount:
  create: false

service:
  type: ClusterIP
  port: 80
  targetPort: 3000  

ingress:
  enabled: false

autoscaling:
  enabled: false

