{{- if eq .Values.deploymentStrategy "canary" }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app
spec:
 replicas: 3
 strategy:
  canary:  
    steps:
    - setWeight: 20
    - pause: { duration: 30s }
    - setWeight: 50
    - pause: { duration: 30s }
    - setWegith: 100

 selector:
   matchLabels:
     app: my-app
 template:
  metadata:
    labels:
      app: my-app
  spec:
    container:
    - name: my-app-c2
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

{{- end }}
