replicaCount: 1

image:
<<<<<<< HEAD
  repository: lehardocker/my-app
  pullPolicy: IfNotPresent
  tag: dev-1  
=======
  repository: nginx
  tag: "1.25"  


>>>>>>> 52ac859 (change values in dev env)
